# Generated by Django 6.0.3 on 2026-04-01 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_photo',
            field=models.ImageField(blank=True, help_text='Photo portrait du vigile (obligatoire a la creation via le tableau de bord).', null=True, upload_to='profiles/'),
        ),
    ]
