# Generated by Django 6.0.3 on 2026-05-12 08:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_domicile'),
        ('sites', '0006_backfill_site_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('super_admin', 'Super admin'), ('admin_societe', 'Admin societe'), ('superviseur', 'Superviseur'), ('controleur', 'Controleur'), ('vigile', 'Vigile')], default='vigile', max_length=32),
        ),
        migrations.CreateModel(
            name='ControllerSiteAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('controller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='controller_site_assignments', to=settings.AUTH_USER_MODEL)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='controller_assignments', to='sites.site')),
            ],
            options={
                'indexes': [models.Index(fields=['site', 'is_active'], name='ctrl_site_active_idx'), models.Index(fields=['controller', 'is_active'], name='ctrl_guard_active_idx')],
                'unique_together': {('controller', 'site')},
            },
        ),
        migrations.CreateModel(
            name='ControllerVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visited_at', models.DateTimeField(auto_now_add=True)),
                ('device_id', models.CharField(blank=True, max_length=120)),
                ('face_score', models.FloatField(blank=True, null=True)),
                ('face_provider', models.CharField(default='face_recognition', max_length=64)),
                ('controller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='controller_visits', to=settings.AUTH_USER_MODEL)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='controller_visits', to='sites.site')),
            ],
            options={
                'indexes': [models.Index(fields=['site', 'visited_at'], name='ctrl_visit_site_time_idx'), models.Index(fields=['controller', 'visited_at'], name='ctrl_visit_guard_time_idx')],
            },
        ),
    ]
