# Generated by Django 6.0.2 on 2026-07-12 07:54

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_user_face_embedding'),
    ]

    operations = [
        migrations.AlterField(
            model_name='controllervisit',
            name='visited_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
