# Generated by Django 6.0.2 on 2026-06-11 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_titularchangelog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='titularchangelog',
            name='kind',
            field=models.CharField(choices=[('titular_promoted', 'Promotion titulaire'), ('titular_reinstated', 'Réintégration titulaire'), ('titular_retired', 'Retrait titulaire')], max_length=32),
        ),
    ]
