# Generated by Django 6.0.3 on 2026-04-03 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkins', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkin',
            name='distance_from_site_meters',
            field=models.FloatField(blank=True, help_text='Distance calculée au centre de géofence du site (m, après enregistrement).', null=True),
        ),
        migrations.AlterField(
            model_name='checkin',
            name='photo',
            field=models.ImageField(blank=True, help_text='Selfie obligatoire a chaque pointage (valide par l API).', null=True, upload_to='checkins/'),
        ),
        migrations.AlterField(
            model_name='checkin',
            name='type',
            field=models.CharField(choices=[('start', 'Start'), ('end', 'End'), ('presence', 'Presence')], max_length=10),
        ),
    ]
