# Generated by Django 6.0.3 on 2026-04-17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shifts", "0001_initial"),
        ("checkins", "0002_geofence_gps_margin_and_distance"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="checkin",
            name="biometric_checked_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="checkin",
            name="biometric_provider",
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name="checkin",
            name="biometric_reason",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="checkin",
            name="biometric_score",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="checkin",
            name="biometric_verified",
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name="BiometricVerification",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("checkin_type", models.CharField(choices=[("start", "Start"), ("end", "End"), ("presence", "Presence")], max_length=10)),
                ("challenge_id", models.CharField(max_length=64, unique=True)),
                ("nonce", models.CharField(max_length=64)),
                ("device_id", models.CharField(blank=True, max_length=120)),
                ("status", models.CharField(choices=[("pending", "Pending"), ("verified", "Verified"), ("rejected", "Rejected")], default="pending", max_length=16)),
                ("score", models.FloatField(blank=True, null=True)),
                ("provider", models.CharField(blank=True, max_length=64)),
                ("reason", models.CharField(blank=True, max_length=255)),
                ("verification_token", models.CharField(blank=True, max_length=128)),
                ("verification_token_expires_at", models.DateTimeField(blank=True, null=True)),
                ("consumed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("verified_at", models.DateTimeField(blank=True, null=True)),
                ("expires_at", models.DateTimeField()),
                ("assignment", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="biometric_verifications", to="shifts.shiftassignment")),
                ("guard", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="biometric_verifications", to=settings.AUTH_USER_MODEL)),
            ],
            options={"ordering": ("-created_at",)},
        ),
    ]
