# Generated by Django 6.0.3 on 2026-03-31 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=300)),
                ('timezone', models.CharField(default='Africa/Abidjan', max_length=64)),
                ('expected_start_time', models.TimeField()),
                ('expected_end_time', models.TimeField()),
                ('late_tolerance_minutes', models.PositiveSmallIntegerField(default=15)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('geofence_radius_meters', models.PositiveIntegerField(default=250)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
