# Generated by Django 6.0.3 on 2026-04-01 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='evening_passation_end',
            field=models.TimeField(default='19:00'),
        ),
        migrations.AddField(
            model_name='site',
            name='evening_passation_start',
            field=models.TimeField(default='18:00', help_text='Debut fenetre passation soir (ex. releve jour → nuit).'),
        ),
        migrations.AddField(
            model_name='site',
            name='morning_passation_end',
            field=models.TimeField(default='07:00'),
        ),
        migrations.AddField(
            model_name='site',
            name='morning_passation_start',
            field=models.TimeField(default='06:00', help_text='Debut fenetre passation matin (ex. releve nuit → jour).'),
        ),
        migrations.AddField(
            model_name='site',
            name='relief_late_alert_minutes',
            field=models.PositiveSmallIntegerField(default=45, help_text="Apres l'heure de prise de service du releve, delai avant alerte admin (minutes)."),
        ),
    ]
