# Generated by Django 6.0.3 on 2026-04-03 06:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_site_evening_passation_end_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='geofence_gps_margin_meters',
            field=models.PositiveSmallIntegerField(default=50, help_text="Marge ajoutée au rayon pour l'imprécision GPS des téléphones (réduit les faux « hors zone »). Mettre 0 pour un contrôle strict."),
        ),
        migrations.AlterField(
            model_name='site',
            name='evening_passation_end',
            field=models.TimeField(default=datetime.time(19, 0)),
        ),
        migrations.AlterField(
            model_name='site',
            name='evening_passation_start',
            field=models.TimeField(default=datetime.time(18, 0), help_text='Début fenêtre passation soir (ex. relève jour → nuit), indicatif planning.'),
        ),
        migrations.AlterField(
            model_name='site',
            name='morning_passation_end',
            field=models.TimeField(default=datetime.time(7, 0)),
        ),
        migrations.AlterField(
            model_name='site',
            name='morning_passation_start',
            field=models.TimeField(default=datetime.time(6, 0), help_text='Début fenêtre passation matin (ex. relève nuit → jour), indicatif planning.'),
        ),
        migrations.AlterField(
            model_name='site',
            name='relief_late_alert_minutes',
            field=models.PositiveSmallIntegerField(default=45, help_text="Après l'heure de prise de service du relève, délai avant alerte admin (minutes)."),
        ),
    ]
