# Generated by Django 6.0.3 on 2026-05-04 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0004_alter_site_geofence_gps_margin_default'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='created_at',
            field=models.DateTimeField(blank=True, help_text='Renseigné pour les sites créés après l’introduction du journal d’activité.', null=True),
        ),
    ]
