# Generated by Django 6.0.2 on 2026-05-28 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0008_site_latitude_longitude_optional'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='day_staff_required',
            field=models.PositiveSmallIntegerField(default=1, help_text='Effectif cible sur le poste jour (06:00-18:00).'),
        ),
        migrations.AddField(
            model_name='site',
            name='night_staff_required',
            field=models.PositiveSmallIntegerField(default=1, help_text='Effectif cible sur le poste nuit (18:00-06:00).'),
        ),
    ]
