# Generated by Django 6.0.2 on 2026-06-11 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0010_site_manager_name_site_sms_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='site_manager_phone',
            field=models.CharField(blank=True, default='', help_text='Téléphone du responsable sur place (contact opérationnel).', max_length=20, verbose_name='Téléphone du responsable du site'),
        ),
    ]
