# Generated by Django 6.0.3 on 2026-04-01 02:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shifts', '0001_initial'),
        ('sites', '0002_site_evening_passation_end_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='shiftassignment',
            name='relieved_by',
            field=models.ForeignKey(blank=True, help_text='Affectation du vigile de RELEVE : sa prise de service est obligatoire avant la fin de service du present creneau.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='outgoing_handover_assignments', to='shifts.shiftassignment'),
        ),
        migrations.AddConstraint(
            model_name='shiftassignment',
            constraint=models.UniqueConstraint(condition=models.Q(('relieved_by__isnull', False)), fields=('relieved_by',), name='uniq_shiftassignment_one_outgoing_per_incoming'),
        ),
    ]
