# Generated by Django 6.0.3 on 2026-04-03 06:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shifts', '0002_shiftassignment_relieved_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shiftassignment',
            name='relieved_by',
            field=models.ForeignKey(blank=True, help_text='Affectation du vigile de relève : sa prise de service est obligatoire avant la fin de service de ce créneau.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='outgoing_handover_assignments', to='shifts.shiftassignment'),
        ),
    ]
