# Generated by Django 6.0.3 on 2026-05-04 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shifts', '0006_fixedpost'),
    ]

    operations = [
        migrations.AddField(
            model_name='shiftassignment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
