# Generated by Django 6.0.2 on 2026-05-28 10:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shifts', '0009_shiftassignment_status_extra'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='shiftassignment',
            name='uniq_shiftassignment_one_outgoing_per_incoming',
        ),
        migrations.AlterField(
            model_name='fixedpost',
            name='replacement_active',
            field=models.BooleanField(default=False, help_text='Si activé, le remplaçant tient le poste sans changer le titulaire (mode temporaire).'),
        ),
        migrations.AlterField(
            model_name='fixedpost',
            name='suspended_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fixedpost',
            name='suspended_titular_guard',
            field=models.ForeignKey(blank=True, help_text="Titulaire d'origine suspendu : le remplaçant de dépêche devient titulaire jusqu'à réintégration.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='suspended_from_fixed_posts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='fixedpost',
            name='suspension_reason',
            field=models.TextField(blank=True, help_text='Justification / motif enregistré lors de la réintégration par le superviseur.'),
        ),
    ]
