# Generated by Django 6.0.2 on 2026-05-28 10:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shifts', '0010_remove_shiftassignment_uniq_shiftassignment_one_outgoing_per_incoming_and_more'),
        ('sites', '0009_site_day_staff_required_site_night_staff_required'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='fixedpost',
            name='uniq_active_fixedpost_per_site_shift',
        ),
        migrations.AddConstraint(
            model_name='fixedpost',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('site', 'shift_type', 'titular_guard'), name='uniq_active_fixedpost_per_site_shift_guard'),
        ),
    ]
